In [1]:
import pandas as pd

df = pd.read_csv("../data/cleaned/cleaned_retail_day3.csv")

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Sales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [3]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 392692 entries, 0 to 392691
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  int64
 1   StockCode    392692 non-null  str
 2   Description  392692 non-null  str
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  datetime64[us]
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  float64
 7   Country      392692 non-null  str
 8   Sales        392692 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(2), str(3)
memory usage: 43.8 MB

In [5]:
df["InvoiceMonth"] = df["InvoiceDate"].dt.to_period("M")
df[["InvoiceDate","InvoiceMonth"]].head()

          InvoiceDate InvoiceMonth
0 2010-12-01 08:26:00      2010-12
1 2010-12-01 08:26:00      2010-12
2 2010-12-01 08:26:00      2010-12
3 2010-12-01 08:26:00      2010-12
4 2010-12-01 08:26:00      2010-12

In [7]:
df["CohortMonth"] = (df.groupby("CustomerID")["InvoiceDate"].transform("min").dt.to_period("M"))
df[["CustomerID","InvoiceMonth","CohortMonth"]].head()

   CustomerID InvoiceMonth CohortMonth
0     17850.0      2010-12     2010-12
1     17850.0      2010-12     2010-12
2     17850.0      2010-12     2010-12
3     17850.0      2010-12     2010-12
4     17850.0      2010-12     2010-12

In [8]:
year_diff = (df["InvoiceMonth"].dt.year -df["CohortMonth"].dt.year)

month_diff = (df["InvoiceMonth"].dt.month -df["CohortMonth"].dt.month)

df["CohortIndex"] = (year_diff * 12 +month_diff + 1)

In [9]:
df[["CustomerID","InvoiceMonth","CohortMonth","CohortIndex"]].head(20)

    CustomerID InvoiceMonth CohortMonth  CohortIndex
0      17850.0      2010-12     2010-12            1
1      17850.0      2010-12     2010-12            1
2      17850.0      2010-12     2010-12            1
3      17850.0      2010-12     2010-12            1
4      17850.0      2010-12     2010-12            1
5      17850.0      2010-12     2010-12            1
6      17850.0      2010-12     2010-12            1
7      17850.0      2010-12     2010-12            1
8      17850.0      2010-12     2010-12            1
9      13047.0      2010-12     2010-12            1
10     13047.0      2010-12     2010-12            1
11     13047.0      2010-12     2010-12            1
12     13047.0      2010-12     2010-12            1
13     13047.0      2010-12     2010-12            1
14     13047.0      2010-12     2010-12            1
15     13047.0      2010-12     2010-12            1
16     13047.0      2010-12     2010-12            1
17     13047.0      2010-12     2010-12            1
18     13047.0      2010-12     2010-12            1
19     13047.0      2010-12     2010-12            1

In [10]:
df.to_csv("../data/cleaned/cohort_ready_dataset.csv",index=False)